### ISSUE TITLE
Formwidget Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by dathwa** [jacobdekeizer/oc-logbook#4]
Hi.
I'm seeing this for the formwidget on the dashboard. Happens when i tried to add it for the 1st time.
`dev.ERROR: ErrorException: Invalid argument supplied for foreach() in ./jacob/logbook/formwidgets/logbook/partials/_logbook.htm:14`

I've added an `if (isset($this->logs)):` to catch it.
But is still shows no entries, even though we have many changes registered.

Any ideas? Thank-you

**Comment by jacobdekeizer** [comment]
Hi, thanks for reporting this issue. I've fixed the issue and released a new version.
