### ISSUE TITLE
Have some error

### ISSUE THREAD

**Issue by semasping** [jacobdekeizer/oc-logbook#5]
ErrorException: Illegal string offset 'changedAttributes' in  ...htdocs/www/plugins/jacob/logbook/models/Log.php:58

**Comment by jacobdekeizer** [comment]
Hello,

Thanks for reporting this issue.
What is your plugin version and octobercms version? And where do you get this error?

**Comment by Dronife** [comment]
I do not quite understand how it works. I tried to call one of the methods, but it does not work. Moreover, the "tutorial" is not clear, it does not say how to use it correctly... Just including class does not do any good

**Comment by Dronife** [comment]
I do not quite understand how I should render the list.

**Comment by jacobdekeizer** [comment]
Hi @Dronife, add the form widget to your fields.yaml of your model with the options described here: https://github.com/jacobdekeizer/oc-logbook#form-widget.

Minimal configuration to only show it on the update screen:
```yaml
_logbook@update:
    type: jacob_logbook_log
```

**Comment by Dronife** [comment]
> ```yaml
> _logbook@update:
>     type: jacob_logbook_log
> ```

Yeah I get it but, how do I call it in backend menu. I can not comprehend how to do it. I am new to OctoberCms haha
