### ISSUE TITLE
Don't work with repeaters

### ISSUE THREAD

**Issue by PubliAlex** [jacobdekeizer/oc-logbook#6]
Hello,

First, congratulation for your module, it seems to be extremly useful.

Unfortunately, it doesn't seems to work with repeater fields, I recorded you a video showing the problem.

https://www.loom.com/share/aa6f7c080756475988481b98fee28e4e

Do you think a fix can be found  ?

Best regards,

**Comment by jacobdekeizer** [comment]
Hi, I added a fix (version 2.1.0) for this issue. Let me know if it works.
