### ISSUE TITLE
Relations not logged

### ISSUE THREAD

**Issue by PubliAlex** [jacobdekeizer/oc-logbook#7]
Hello,

I have a model with 3 relations (many to many).

I specified them in the showLogRelations item as you can see, but changes in my relations are not logged.

![image](https://user-images.githubusercontent.com/55833027/155812314-dbea5ccf-de46-42f9-aff5-afa9967c9770.png)

Best regards,

**Comment by jacobdekeizer** [comment]
Did you add the LogChanges trait to the models of the specified relations? 

Author, Category and Tag models should have the LogChanges trait.

**Comment by PubliAlex** [comment]
Hello,

I added the trait to that models, but still no log :/

This is many to many relationship, so I have intermediate table to make the relations, can it be the cause of the problem ?
