### ISSUE TITLE
Allow HTML in $value returned by changeLogBookDisplayValue() method

### ISSUE THREAD

**Issue by PubliAlex** [jacobdekeizer/oc-logbook#8]
Hello,

I noticed that you can't display HTML even by tweaking the $value variable in changeLogBookDisplayValue() method.

It's due to the use of escaping method in partial.

It's quite annoying because it prevent to add line return or others useful things when you deal with complex data of content

It would be great to remove this escaping method and let people have control about what to render

Thank you

**Comment by jacobdekeizer** [comment]
I've added this feature to version 2.1.0 so you can return a Htmlable class to support HTML content. Be sure to escape user content with the escape helper `e()` to prevent XSS attacks. Let me know if it works.

E.g. Model

```php
public static function changeLogBookDisplayValue($column, $value)
{
    if ($column === 'data') {
        return new DisplayJsonableValue($value ? json_decode($value) : null);
    }

    return $value;
} 
```

E.g. a custom class to handle jsonable content

```php
use Illuminate\Contracts\Support\Htmlable;

class DisplayJsonableValue implements Htmlable
{
    private ?array $jsonValue;

    public function __construct(?array $jsonValue)
    {
        $this->jsonValue = $jsonValue;
    }

    public function toHtml(): string
    {
        if ($this->jsonValue === null) {
            return '-';
        }

        $content = '<ul>';

        foreach ($this->jsonValue as $columns) {
            $content .= '<li>';
            foreach ($columns as $column => $value) {
                $content .= '<bold>' . e((string) $column) . '</bold>: ' . e((string) $value) . '<br/>';
            }
            $content .= '</li>';
        }

        return $content . '</ul>';
    }
}
```
